-- Add new values to AcademicPosition enum
-- PostgreSQL requires separate ALTER TYPE statements per value
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'PROFESSOR_IN_PRACTICE';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'VISITING_FULLTIME_PROFESSOR';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'VISITING_ASSOCIATE_PROFESSOR';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'HEAD_OF_DEPARTMENT';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'ASSOCIATE_DEAN';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'ASSISTANT_DEAN';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'DEAN';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'DIRECTOR';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'ASSOCIATE_DIRECTOR';
ALTER TYPE "AcademicPosition" ADD VALUE IF NOT EXISTS 'POSTDOC';
