export const CONSTANTS = {
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN ?? '15m',
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN ?? '7d',
  BCRYPT_ROUNDS: 12,
  PAGINATION_DEFAULT_LIMIT: 20,
  PAGINATION_MAX_LIMIT: 100,
  DASHBOARD_CACHE_TTL: 300, // 5 minutes in seconds
  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
  RATE_LIMIT_MAX_AUTH: 20,
  RATE_LIMIT_MAX_API: 300,
  UPLOAD_MAX_SIZE: 5 * 1024 * 1024, // 5MB
};
